### ISSUE TITLE
Notifications that will be removed by the app from the notification center are not removed from category view

### ISSUE THREAD

**Issue by Raamakrishnan** [balamurugan15/Notifix#12]
Version 0.7b
Notifications that are generally removed by the corresponding app from the notification center, are not removed from the category view. Steps to reproduce:
1. When you receive a message from whatsapp, allow it to be categorised.
2. Open Whatsapp by clicking on the icon from the launcher (not through the notification)
3. The notification still remains in the category view. Had the notification remained in the notification center, whatsapp would have removed it.

Another example:
In the following screenshot, you can notice a notification "Google Play Store: Gmail: Updating Gmail..". This notification would have been automatically removed by the Play Store from the notification centre, had it not been captured by notifix. And yet it is still visible in the category.
<img src="https://user-images.githubusercontent.com/9772489/38160360-ff213908-34d9-11e8-96f5-6f439b853aa9.png" height="500" />

**Comment by balamurugan15** [comment]
Whatsapp messages will be automatically removed from category view once you open WhatsApp (from the launcher) [wait for a couple of secs]. 

And that updating thing is exclusive to Google Play. I can't predict which notifications will be removed by the app which posted it actually. For play store scenario, I can hardcode it if that's a big issue!

**Comment by balamurugan15** [comment]
A separate issue for Play notifications is open. So closing this. We'll reopen if WhatsApp is causing such an issue again.
